services:
  - type: web
    name: telegram-bot
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TG_BOT_TOKEN
        sync: false
      - key: BOT_MODERATORS
        sync: false
      - key: JAVA_OPTS
        value: "-Xmx256m -Xms128m"
    healthCheckPath: /
    autoDeploy: true
